import './globals.css';
import { Inter } from 'next/font/google';
import { FileHint } from '../ui/FileHint';
import Link from 'next/link';
import { MainNav } from './_components/MainNav';

const inter = Inter({ subsets: ['latin'] });

// SEO 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root Document Shell
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col gap-4">
          {/* Top Bar */}
          <div className='px-4 pt-4'>
            <div className='px-8 py-4 bg-zinc-900 rounded-xl'>
              <div className="mb-4 flex items-center gap-4">
                <div className='relative'>
                  <div className="absolute -left-5 top-1/2 -translate-y-1/2">
                    <div className="animate-ping w-2 h-2 rounded-full bg-sky-400 border-sky-200 border-2 opacity-75"></div>
                  </div>
                  <p>Root Layout <FileHint fileName='app/layout.tsx' /></p>
                </div>
              </div>
              <MainNav />
            </div>
          </div>
          {/* Content */}
          <div className="flex-grow min-h-0">
            {children}
          </div>
        </div>
      </body>
    </html >
  );
}
